<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Gustavo Frosi">
<meta name="description" content="Construindo uma regressão linear simples passo a passo">

<title>Do ponto à linha: criando uma regressão para além de clicar em botão – Gustavo Frosi</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<link href="../../ima/FS2.png" rel="icon" type="image/png">
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-0db66c32e16a2551af7299a43e6f95a1.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-dab333370b46a58f04c2e79b6e18fa8e.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-0db66c32e16a2551af7299a43e6f95a1.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5c083f410bf45b7b280f85a8f58eb4c3.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-4c7b4c9c45ffc6b0ca0e2b6032e018e7.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-5c083f410bf45b7b280f85a8f58eb4c3.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-8L8YC0LJJY"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-8L8YC0LJJY', { 'anonymize_ip': true});
</script>
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: #FFFFFF;
      }

      .quarto-title-block .quarto-title-banner {
        color: #FFFFFF;
      }
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
<meta property="og:title" content="Do ponto à linha: criando uma regressão para além de clicar em botão – Gustavo Frosi">
<meta property="og:description" content="Construindo uma regressão linear simples passo a passo">
<meta property="og:image" content="https://gustavofrosi.com.br/recap/2026-07-06-reg-line-conta/Reg_mao.jpeg">
<meta property="og:site_name" content="Gustavo Frosi">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Gustavo Frosi</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Alternar de navegação" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../formacao.html"> 
<span class="menu-text">Formação</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../CV/index.html"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projetos.html"> 
<span class="menu-text">Projetos</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-trabalhos-científicos" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Trabalhos Científicos</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-trabalhos-científicos">    
        <li>
    <a class="dropdown-item" href="../../artigos.html">
 <span class="dropdown-text">Artigos</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../resumos.html">
 <span class="dropdown-text">Resumos</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../recap.html"> 
<span class="menu-text">Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../gallery.html"> 
<span class="menu-text">Gallery</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="../../rss.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo escuro"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Alternar modo de leitor">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-page-left">
      <h1 class="title">Do ponto à linha: criando uma regressão para além de clicar em botão</h1>
                  <div>
        <div class="description">
          Construindo uma regressão linear simples passo a passo
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">R</div>
                <div class="quarto-category">Regressão Linear</div>
                <div class="quarto-category">Estatística</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta column-page-left">

      <div>
      <div class="quarto-title-meta-heading">Autor</div>
      <div class="quarto-title-meta-contents">
               <p>Gustavo Frosi <a href="mailto:gustavofrosi@hotmail.com" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Data de Publicação</div>
      <div class="quarto-title-meta-contents">
        <p class="date">6 de julho de 2026</p>
      </div>
    </div>
    
      
      <div>
      <div class="quarto-title-meta-heading">Doi</div>
      <div class="quarto-title-meta-contents">
        <p class="doi">
          <a href="https://doi.org/10.59350/xp1jx-gs759">10.59350/xp1jx-gs759</a>
        </p>
      </div>
    </div>
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Nesta página</h2>
   
  <ul>
  <li><a href="#por-que-do-ponto-a-linha" id="toc-por-que-do-ponto-a-linha" class="nav-link active" data-scroll-target="#por-que-do-ponto-a-linha">Por que do ponto a linha?</a></li>
  <li><a href="#a-regressão-linear" id="toc-a-regressão-linear" class="nav-link" data-scroll-target="#a-regressão-linear">A regressão linear</a>
  <ul class="collapse">
  <li><a href="#nomenclaturas" id="toc-nomenclaturas" class="nav-link" data-scroll-target="#nomenclaturas">Nomenclaturas</a></li>
  </ul></li>
  <li><a href="#desenvolvendo-a-regressão-linear" id="toc-desenvolvendo-a-regressão-linear" class="nav-link" data-scroll-target="#desenvolvendo-a-regressão-linear">Desenvolvendo a regressão linear</a>
  <ul class="collapse">
  <li><a href="#dados-e-a-pergunta" id="toc-dados-e-a-pergunta" class="nav-link" data-scroll-target="#dados-e-a-pergunta">Dados e a pergunta</a></li>
  <li><a href="#estimando-os-betas" id="toc-estimando-os-betas" class="nav-link" data-scroll-target="#estimando-os-betas">Estimando os <span class="math inline">\(\beta\)</span>s</a></li>
  <li><a href="#estimando-os-betas-do-problema" id="toc-estimando-os-betas-do-problema" class="nav-link" data-scroll-target="#estimando-os-betas-do-problema">Estimando os betas do problema</a></li>
  <li><a href="#modelo-final" id="toc-modelo-final" class="nav-link" data-scroll-target="#modelo-final">Modelo final</a></li>
  <li><a href="#análise-de-variância-da-regressão" id="toc-análise-de-variância-da-regressão" class="nav-link" data-scroll-target="#análise-de-variância-da-regressão">Análise de variância da regressão</a>
  <ul class="collapse">
  <li><a href="#coeficiente-de-determinação-r2" id="toc-coeficiente-de-determinação-r2" class="nav-link" data-scroll-target="#coeficiente-de-determinação-r2">Coeficiente de determinação <span class="math inline">\((R^2)\)</span></a></li>
  <li><a href="#coeficiente-de-determinação-r2-do-exemplo" id="toc-coeficiente-de-determinação-r2-do-exemplo" class="nav-link" data-scroll-target="#coeficiente-de-determinação-r2-do-exemplo">Coeficiente de determinação <span class="math inline">\((R^2)\)</span> do exemplo</a></li>
  <li><a href="#teste-f" id="toc-teste-f" class="nav-link" data-scroll-target="#teste-f">Teste <span class="math inline">\(F\)</span></a></li>
  </ul></li>
  <li><a href="#significância-dos-betas-do-modelo" id="toc-significância-dos-betas-do-modelo" class="nav-link" data-scroll-target="#significância-dos-betas-do-modelo">Significância dos <span class="math inline">\(\beta\)</span>s do modelo</a>
  <ul class="collapse">
  <li><a href="#teste-de-significância-para-beta_0-e-beta_1" id="toc-teste-de-significância-para-beta_0-e-beta_1" class="nav-link" data-scroll-target="#teste-de-significância-para-beta_0-e-beta_1">Teste de significância para <span class="math inline">\(\beta_0\)</span> e <span class="math inline">\(\beta_1\)</span></a></li>
  <li><a href="#teste-de-significância-para-beta_0-e-beta_1-do-problema" id="toc-teste-de-significância-para-beta_0-e-beta_1-do-problema" class="nav-link" data-scroll-target="#teste-de-significância-para-beta_0-e-beta_1-do-problema">Teste de significância para <span class="math inline">\(\beta_0\)</span> e <span class="math inline">\(\beta_1\)</span> do problema</a></li>
  <li><a href="#intervalo-de-confiança-do-beta-e-da-predição-ic" id="toc-intervalo-de-confiança-do-beta-e-da-predição-ic" class="nav-link" data-scroll-target="#intervalo-de-confiança-do-beta-e-da-predição-ic">Intervalo de confiança do beta e da predição (IC)</a></li>
  <li><a href="#intervalo-de-confiança-do-beta-do-modelo" id="toc-intervalo-de-confiança-do-beta-do-modelo" class="nav-link" data-scroll-target="#intervalo-de-confiança-do-beta-do-modelo">Intervalo de confiança do beta do modelo</a></li>
  <li><a href="#intervalo-de-confiança-para-resposta-média" id="toc-intervalo-de-confiança-para-resposta-média" class="nav-link" data-scroll-target="#intervalo-de-confiança-para-resposta-média">Intervalo de confiança para resposta média</a></li>
  <li><a href="#intervalo-de-confiança-para-resposta-média-do-modelo" id="toc-intervalo-de-confiança-para-resposta-média-do-modelo" class="nav-link" data-scroll-target="#intervalo-de-confiança-para-resposta-média-do-modelo">Intervalo de confiança para resposta média do modelo</a></li>
  </ul></li>
  <li><a href="#resultado-final-da-análise" id="toc-resultado-final-da-análise" class="nav-link" data-scroll-target="#resultado-final-da-análise">Resultado final da análise</a></li>
  </ul></li>
  <li><a href="#regressão-linear-simples-define-causa-bônus" id="toc-regressão-linear-simples-define-causa-bônus" class="nav-link" data-scroll-target="#regressão-linear-simples-define-causa-bônus">Regressão linear simples define causa? (bônus)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block column-page-left" id="quarto-document-content">






<section id="por-que-do-ponto-a-linha" class="level1">
<h1>Por que do ponto a linha?</h1>
<p>Entender a regressão aos “pedaços” funciona, mas há limites. Aqui, reúno algumas “peças” de como a regressão linear funciona. Assim, um entendimento um pouco mais amplo dos cálculos que dão origem à regressão linear é exposto. A ideia é ir do plot dos pontos até as linhas de regressão e de intervalos de confiança. Isso pode servir como base para entender não só o funcionamento como também os usos e as limitações.</p>
<p>A intenção é apenas uma: entender de onde “surgem” as “coisas” em uma regressão linear simples. O aprofundamento foi até o limite do que meu conhecimento permitiu. E, como não sou matemático nem parente próximo, por enquanto assuntos mais complexos e fundamentais do cálculo e da álgebra ficarão de lado.</p>
</section>
<section id="a-regressão-linear" class="level1">
<h1>A regressão linear</h1>
<p>A regressão linear é utilizada para quantificar e inferir a relação entre uma variável dependente e uma ou mais variáveis independentes. O princípio básico da regressão pode ser representado por:</p>
<p><span id="eq-funcao"><span class="math display">\[
y = f(x)
\tag{1}\]</span></span></p>
<p>Basicamente, o que se busca na regressão é encontrar uma reta em que o valor dos resíduos seja o menor possível. A função que descreve isso é dada como:</p>
<p><span id="eq-emq"><span class="math display">\[
\min_{\beta_0,\beta_1} \sum_{i=1}^{n} (y_i-(\beta_0-\beta_1x_i))^2
\tag{2}\]</span></span></p>
<p>Onde os termos <span class="math inline">\(\min_{\beta_0,\beta_1}\)</span> dizem respeito a encontrar valores de <span class="math inline">\(\beta\)</span> que minimizem a função; por minimizar entende-se retornar o menor valor da função. Já <span class="math inline">\(\sum_{i=1}^{n}\)</span> é basicamente somar o resultado de cada operação dos <span class="math inline">\(()\)</span>. E, dentro dos <span class="math inline">\(()\)</span>, temos a operação que é o valor observado dado por <span class="math inline">\(y_i\)</span> menos o <span class="math inline">\(y\)</span> estimado pelos <span class="math inline">\(\beta_0;~\beta_1x_i\)</span>. Eleva-se ao quadrado para trabalhar com os valores negativos e por questões mais aprofundadas de derivada.</p>
<p>Ao fim, queremos os valores de <span class="math inline">\(\beta\)</span> que levem à menor diferença entre o <span class="math inline">\(y\)</span> estimado e o <span class="math inline">\(y\)</span> observado.</p>
<!-- Ou seja, uma função que a partir de $x$ eu obtenha os valores de $y$. Essa notação por si só já é interessante. Como posso manipular $x$ de tal forma que eu encontre $y$? Isso é fantástico. O ponto importante é que essa função precisa existir e, para além disso, eu preciso ser capaz de encontrá-la e "validá-la". -->
<div id="wrn-exp" class="callout callout-style-default callout-note callout-titled" title="Finalidade da regressão">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota&nbsp;1: Finalidade da regressão
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Um ponto muito importante aqui é dizer que a regressão pode ser utilizada para: descrever, explicar ou predizer dados. E isso é apenas uma questão de narrativa ou objetivo da análise, dependendo puramente de quem a interpreta ou publica (<span class="citation" data-cites="kasza">Kasza e Wolfe (<a href="#ref-kasza" role="doc-biblioref">2014</a>)</span>, <span class="citation" data-cites="shmueli">Shmueli (<a href="#ref-shmueli" role="doc-biblioref">2010</a>)</span>, <span class="citation" data-cites="altay">Altay L. Souza (<a href="#ref-altay" role="doc-biblioref">2025</a>)</span>).</p>
</div>
</div>
</div>
<p>O modelo matemático da regressão linear pode ser expresso como:</p>
<p><span id="eq-regline"><span class="math display">\[
y = \beta_{0} + \beta_{1} x + \epsilon
\tag{3}\]</span></span></p>
<p>Além disso, é importante que os erros possuam uma distribuição normal com média zero e variância constante.</p>
<p><span id="eq-erros"><span class="math display">\[
\epsilon \sim N(0,\sigma^2)
\tag{4}\]</span></span></p>
<p>No entanto, o modelo acima parte do pressuposto de que vamos encontrar os verdadeiros e pontuais valores para os <span class="math inline">\(\beta\)</span>s, o que não é necessariamente verdade. Na realidade, o que realizamos na maior parte dos casos é encontrar os valores dos <span class="math inline">\(\beta\)</span>s de uma amostra que, em teoria, deve ser uma representação da população (faça uma boa amostragem!). Com isso, o que encontramos na análise são valores médios para os <span class="math inline">\(\beta\)</span>s que, dentro de intervalos de confiança, são encontrados como os verdadeiros valores na população. Sendo assim, a equação que utilizamos deve ser:</p>
<p><span id="eq-regestimada"><span class="math display">\[
\hat{y} = \hat{\beta_{0}} + \hat{\beta_{1}}x + \epsilon
\tag{5}\]</span></span></p>
<p>Uma definição mais simples é realizada na seção abaixo.</p>
<section id="nomenclaturas" class="level2">
<h2 class="anchored" data-anchor-id="nomenclaturas">Nomenclaturas</h2>
<p>É importante definir alguns símbolos que denotam um significado distinto às variáveis, às estimativas dessas e ao modelo de regressão.</p>
<ul>
<li><p>O <span class="math inline">\(y\)</span> é a variável dependente ou resposta;</p></li>
<li><p>O <span class="math inline">\(\hat{y}\)</span> é o valor da estimativa/predição;</p></li>
<li><p>O <span class="math inline">\(y_{i}\)</span> indica o valor observado da observação <span class="math inline">\(i\)</span>, onde <span class="math inline">\(i\)</span> assume valores diferentes para cada observação do conjunto de dados;</p></li>
<li><p>O <span class="math inline">\(\bar{y}\)</span> é a média dos valores de <span class="math inline">\(y\)</span> da amostra;</p></li>
<li><p>O <span class="math inline">\(x\)</span> é a variável independente ou explicativa/preditora. Podemos ter mais de um <span class="math inline">\(x\)</span> e poderíamos denotá-los como: <span class="math inline">\(x_{1}, x_{2}, ..., x_{n}\)</span>. Como a ideia é focar na regressão simples, apenas um <span class="math inline">\(x\)</span> será usado;</p></li>
<li><p>O <span class="math inline">\(x_{i}\)</span> indica o valor de <span class="math inline">\(x\)</span> da observação <span class="math inline">\(i\)</span>, onde <span class="math inline">\(i\)</span> assume valores diferentes para cada observação do conjunto de dados;</p></li>
<li><p>O <span class="math inline">\(\bar{x}\)</span> é a média dos valores de <span class="math inline">\(x\)</span> da amostra;</p></li>
<li><p><span class="math inline">\(f(x)\)</span> é o modelo, ou seja, a função de <span class="math inline">\(x\)</span>;</p></li>
<li><p><span class="math inline">\(\epsilon\)</span> é o erro do modelo (diferença entre o <span class="math inline">\(y\)</span> previsto e o observado);</p></li>
<li><p><span class="math inline">\(\epsilon_{i}\)</span> é o erro para cada observação;</p></li>
<li><p><span class="math inline">\(\beta_{0}\)</span> é o intercepto do modelo (ponto em <span class="math inline">\(y\)</span> onde a reta passa quando <span class="math inline">\(x\)</span> assume valor <span class="math inline">\(0\)</span>). Caso a relação do modelo exista na realidade, o <span class="math inline">\(\beta_{0}\)</span> é o valor real da população;</p></li>
<li><p><span class="math inline">\(\hat{\beta_{0}}\)</span> é o intercepto estimado da amostra;</p></li>
<li><p><span class="math inline">\(\beta_{1}\)</span> é o coeficiente angular do modelo (variação em <span class="math inline">\(y\)</span> com o aumento de uma unidade em <span class="math inline">\(x\)</span>). Caso a relação do modelo exista na realidade, o <span class="math inline">\(\beta_{1}\)</span> é o valor real da população;</p></li>
<li><p><span class="math inline">\(\hat{\beta_{1}}\)</span> é o coeficiente angular estimado da amostra;</p></li>
</ul>
</section>
</section>
<section id="desenvolvendo-a-regressão-linear" class="level1">
<h1>Desenvolvendo a regressão linear</h1>
<section id="dados-e-a-pergunta" class="level2">
<h2 class="anchored" data-anchor-id="dados-e-a-pergunta">Dados e a pergunta</h2>
<p>Para desvendar os mistérios dessa tal regressão linear simples, vamos utilizar os dados de exemplo da <a href="#tbl-teste" class="quarto-xref">Tabela&nbsp;1</a>. São apenas 6 linhas de dados, o que é bem pouco; porém, a ideia central é desenvolver a conta e, para facilitar isso, faz-se necessário um exemplo com poucos dados. Nesses dados, imaginamos que temos como variável <span class="math inline">\(x\)</span> a idade de diferentes pessoas e em <span class="math inline">\(y\)</span> a altura de cada uma em cm.</p>
<div class="cell">
<div id="tbl-teste" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-teste-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;1: Dados para a regressão
</figcaption>
<div aria-describedby="tbl-teste-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="inrgqbnsnr" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#inrgqbnsnr table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#inrgqbnsnr thead, #inrgqbnsnr tbody, #inrgqbnsnr tfoot, #inrgqbnsnr tr, #inrgqbnsnr td, #inrgqbnsnr th {
  border-style: none;
}

#inrgqbnsnr p {
  margin: 0;
  padding: 0;
}

#inrgqbnsnr .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#inrgqbnsnr .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#inrgqbnsnr .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#inrgqbnsnr .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#inrgqbnsnr .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#inrgqbnsnr .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#inrgqbnsnr .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#inrgqbnsnr .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#inrgqbnsnr .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#inrgqbnsnr .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#inrgqbnsnr .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#inrgqbnsnr .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#inrgqbnsnr .gt_spanner_row {
  border-bottom-style: hidden;
}

#inrgqbnsnr .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#inrgqbnsnr .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#inrgqbnsnr .gt_from_md > :first-child {
  margin-top: 0;
}

#inrgqbnsnr .gt_from_md > :last-child {
  margin-bottom: 0;
}

#inrgqbnsnr .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#inrgqbnsnr .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#inrgqbnsnr .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#inrgqbnsnr .gt_row_group_first td {
  border-top-width: 2px;
}

#inrgqbnsnr .gt_row_group_first th {
  border-top-width: 2px;
}

#inrgqbnsnr .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#inrgqbnsnr .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#inrgqbnsnr .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#inrgqbnsnr .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#inrgqbnsnr .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#inrgqbnsnr .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#inrgqbnsnr .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#inrgqbnsnr .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#inrgqbnsnr .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#inrgqbnsnr .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#inrgqbnsnr .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#inrgqbnsnr .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#inrgqbnsnr .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#inrgqbnsnr .gt_left {
  text-align: left;
}

#inrgqbnsnr .gt_center {
  text-align: center;
}

#inrgqbnsnr .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#inrgqbnsnr .gt_font_normal {
  font-weight: normal;
}

#inrgqbnsnr .gt_font_bold {
  font-weight: bold;
}

#inrgqbnsnr .gt_font_italic {
  font-style: italic;
}

#inrgqbnsnr .gt_super {
  font-size: 65%;
}

#inrgqbnsnr .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#inrgqbnsnr .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#inrgqbnsnr .gt_indent_1 {
  text-indent: 5px;
}

#inrgqbnsnr .gt_indent_2 {
  text-indent: 10px;
}

#inrgqbnsnr .gt_indent_3 {
  text-indent: 15px;
}

#inrgqbnsnr .gt_indent_4 {
  text-indent: 20px;
}

#inrgqbnsnr .gt_indent_5 {
  text-indent: 25px;
}

#inrgqbnsnr .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#inrgqbnsnr div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table cell caption-top table table-sm table-striped small" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="gt_heading header">
<td colspan="2" class="gt_heading gt_title gt_font_normal gt_bottom_border">Dados de exemplo</td>
</tr>
<tr class="gt_col_headings even">
<th id="x" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">x - Idade (anos)<br>
(Variável independente)</th>
<th id="y" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">y - Altura (cm)<br>
(Variável dependente)</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_center" headers="x">5</td>
<td class="gt_row gt_center" headers="y">110</td>
</tr>
<tr class="even">
<td class="gt_row gt_center" headers="x">7</td>
<td class="gt_row gt_center" headers="y">120</td>
</tr>
<tr class="odd">
<td class="gt_row gt_center" headers="x">9</td>
<td class="gt_row gt_center" headers="y">120</td>
</tr>
<tr class="even">
<td class="gt_row gt_center" headers="x">11</td>
<td class="gt_row gt_center" headers="y">135</td>
</tr>
<tr class="odd">
<td class="gt_row gt_center" headers="x">13</td>
<td class="gt_row gt_center" headers="y">155</td>
</tr>
<tr class="even">
<td class="gt_row gt_center" headers="x">15</td>
<td class="gt_row gt_center" headers="y">168</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>O primeiro passo é se perguntar: <strong>A idade das pessoas tem efeito na altura?</strong></p>
<p>Essa pergunta, para ser respondida por meio da regressão, deve ser expressa em termos da equação como: <span id="eq-regdados"><span class="math display">\[
Altura = \beta_{0} + \beta_{1} Idade + \epsilon
\tag{6}\]</span></span></p>
<div id="wrn-exp" class="callout callout-style-default callout-note callout-titled" title="Para experimentos">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota&nbsp;2: Para experimentos
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Vale lembrar que em um experimento a pergunta é feita antes da análise e que o delineamento do experimento vai refletir a análise a ser utilizada.</p>
</div>
</div>
</div>
<p>Como temos apenas uma variável <span class="math inline">\(x\)</span>, podemos criar um gráfico traçando a interseção entre o eixo das abscissas ou <span class="math inline">\(x\)</span> e o eixo das ordenadas ou <span class="math inline">\(y\)</span> <span class="math inline">\((x;y)\)</span> (<a href="#fig-dispersao" class="quarto-xref">Figura&nbsp;1</a>) e verificar como os dados estão dispersos.</p>
<div id="fig-dispersao" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dispersao-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="disper.jpeg" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figura&nbsp;1: Gráfico de dispersão dos dados"><img src="disper.jpeg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dispersao-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1: Gráfico de dispersão dos dados
</figcaption>
</figure>
</div>
<p>O que podemos analisar é que parece existir uma relação entre a idade e a altura. Parece que as pessoas mais velhas também são mais altas, pelo menos nessa amostra. Esse é um primeiro indício de que podemos fazer uma regressão com esses dados.</p>
</section>
<section id="estimando-os-betas" class="level2">
<h2 class="anchored" data-anchor-id="estimando-os-betas">Estimando os <span class="math inline">\(\beta\)</span>s</h2>
<p>Para estimar o <span class="math inline">\(\beta_1\)</span> utilizamos a <a href="#eq-beta1" class="quarto-xref">Equação&nbsp;7</a>:</p>
<p><span id="eq-beta1"><span class="math display">\[
\hat{\beta_{1}} = \frac{\sum(x_{i}-\bar{x})(y_{i}-\bar{y})}{\sum(x_{i}-\bar{x})^2}
\tag{7}\]</span></span></p>
<p>Aqui, observamos que no numerador temos o somatório do produto entre os desvios de <span class="math inline">\(x\)</span> e de <span class="math inline">\(y\)</span>. A ideia é verificar o quanto os valores observados estão distantes da média, para cada eixo, e depois multiplicar essas distâncias para observar se a relação é positiva ou negativa. Assim, obtém-se se a relação é de crescimento ou de decrescimento. Ao fim, soma-se tudo, pois o objetivo é usar todos os dados para obter uma única reta. Já no denominador temos os desvios de <span class="math inline">\(x\)</span> ao quadrado, o que serve para verificar o quanto <span class="math inline">\(x\)</span> varia de forma isolada. A divisão é como se tivéssemos o quanto <span class="math inline">\(x\)</span> e <span class="math inline">\(y\)</span> variam juntos dividido pelo quanto <span class="math inline">\(x\)</span> varia sozinho. Ao fim, o resultado é o quanto <span class="math inline">\(y\)</span> muda para cada unidade de mudança em <span class="math inline">\(x\)</span>.</p>
<p>Já para o <span class="math inline">\(\beta_0\)</span> é muito mais simples: basta isolá-lo e substituir o <span class="math inline">\(\beta_1\)</span> encontrado pela <a href="#eq-beta1" class="quarto-xref">Equação&nbsp;7</a> em <a href="#eq-beta0" class="quarto-xref">Equação&nbsp;8</a>:</p>
<p><span id="eq-beta0"><span class="math display">\[
\hat{\beta_{0}} = \bar{y} - \hat{\beta_{1}}  \bar{x}
\tag{8}\]</span></span></p>
<p>Mas também podemos encontrar o <span class="math inline">\(\beta_0\)</span> por meio da <a href="#eq-beta02" class="quarto-xref">Equação&nbsp;9</a>.</p>
<p><span id="eq-beta02"><span class="math display">\[
\hat{\beta}_0 =
\frac{
\sum y_i \sum x_i^2 -
\sum x_i \sum x_i y_i
}{
n \sum x_i^2 -
(\sum x_i)^2
}
\tag{9}\]</span></span></p>
<p>No numerador temos o somatório dos valores observados de <span class="math inline">\(y\)</span> (<span class="math inline">\(\sum y_i\)</span>) multiplicado pelo somatório do quadrado dos valores observados de <span class="math inline">\(x\)</span> (<span class="math inline">\(\sum x_i^2\)</span>), tudo isso menos o somatório dos valores observados de <span class="math inline">\(x\)</span> (<span class="math inline">\(\sum x_i\)</span>) multiplicado pela soma dos produtos de <span class="math inline">\(x\)</span> e <span class="math inline">\(y\)</span> (<span class="math inline">\(\sum x_i y_i\)</span>). Já no denominador temos o número de observações (<span class="math inline">\(n\)</span>) multiplicado pelo somatório das observações de <span class="math inline">\(x\)</span> ao quadrado (<span class="math inline">\(\sum x_i^2\)</span>) menos o quadrado da soma de <span class="math inline">\(x\)</span> (<span class="math inline">\((\sum x_i)^2\)</span>). A ideia aqui é explicar quanto da altura da reta não se deve à inclinação (<span class="math inline">\(\hat{\beta_1}\)</span>).</p>
</section>
<section id="estimando-os-betas-do-problema" class="level2">
<h2 class="anchored" data-anchor-id="estimando-os-betas-do-problema">Estimando os betas do problema</h2>
<p>A ideia é encontrar quais os melhores valores para <span class="math inline">\(\hat{\beta_{0}}\)</span> e para <span class="math inline">\(\hat{\beta_{1}}\)</span> com o menor erro possível. Para isso será utilizada a <a href="#eq-beta1" class="quarto-xref">Equação&nbsp;7</a> e a <a href="#eq-beta0" class="quarto-xref">Equação&nbsp;8</a>.</p>
<p>Primeiro, calcula-se a média de <span class="math inline">\(x\)</span> e de <span class="math inline">\(y\)</span>:</p>
<div class="columns">
<div class="column" style="width:20%;">
<p><span class="math display">\[\bar{x} = \frac{\sum x_i}{n}\]</span></p>
<p><span class="math display">\[\bar{y} = \frac{\sum y_i}{n}\]</span></p>
</div><div class="column" style="width:80%;">
<p><span id="eq-mediax"><span class="math display">\[
\bar{x} = \frac{5+7+9+11+13+15}{6} = 10
\tag{10}\]</span></span></p>
<p><span id="eq-mediay"><span class="math display">\[
\bar{y} = \frac{110+120+120+135+155+168}{6} = 134.67
\tag{11}\]</span></span></p>
</div>
</div>
<p>Depois, iniciamos o cálculo do <span class="math inline">\(\hat{\beta_1}\)</span>, e o primeiro passo é fazer a soma do produto dos desvios de cada observação em relação à média de <span class="math inline">\(x\)</span> e de <span class="math inline">\(y\)</span>. Graficamente podemos observar o que está sendo realizado, conforme a <a href="#fig-mediamedia" class="quarto-xref">Figura&nbsp;2</a>.</p>
<div id="fig-mediamedia" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mediamedia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="media_media_desvi.jpeg" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figura&nbsp;2: A) Dispersão dos dados e linhas de médias; B) Adição de linhas de desvios."><img src="media_media_desvi.jpeg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mediamedia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;2: A) Dispersão dos dados e linhas de médias; B) Adição de linhas de desvios.
</figcaption>
</figure>
</div>
<p>O numerador para o <span class="math inline">\(\hat{\beta_1}\)</span> tem o valor de <span class="math inline">\(410\)</span> e foi encontrado da seguinte forma:</p>
<p><span class="math display">\[
\begin{aligned}
\sum(x_{i}-\bar{x})(y_{i}-\bar{y}) =\;&amp;
(5-10)*(110-134.67) + (7-10)*(120-134.67) + {} \\
&amp;
(9-10)*(120-134.67) + (11-10)*(135-134.67) + {} \\
&amp;
(13-10)*(155-134.67) + (15-10)*(168-134.67)
\end{aligned}
\]</span></p>
<p><span class="math display">\[
\sum(x_{i}-\bar{x})(y_{i}-\bar{y}) = 123.33+44+16.67+0.33+61+166.67= 410
\]</span></p>
<p>Já para o denominador temos um valor de <span class="math inline">\(70\)</span>, encontrado com base no seguinte cálculo:</p>
<p><span class="math display">\[
\begin{aligned}
\sum(x_i - \bar{x})^2 = \;&amp; (5 - 10)^2 + (7-10)^2 + (9-10)^2 + {} \\
&amp;
(11-10)^2 + (13-10)^2 + (15-10)^2
\end{aligned}
\]</span></p>
<p><span id="eq-somadesviox"><span class="math display">\[
\sum(x_i - \bar{x})^2 = 25+9+1+1+9+25 = 70
\tag{12}\]</span></span></p>
<p>Agora, para encontrar o <span class="math inline">\(\beta_1\)</span>, basta fazer a divisão, que resulta em 5.86.</p>
<p><span class="math display">\[\hat{\beta_1} = \frac{410}{70} = 5.86\]</span></p>
<p>Para o <span class="math inline">\(\beta_0\)</span> é só fazer a substituição na equação de regressão (<a href="#eq-beta0" class="quarto-xref">Equação&nbsp;8</a>) e obtemos o valor de 76.10.</p>
<p><span class="math display">\[
\hat{\beta_{0}} = 134.67 - 5.86 * 10 = 76.10
\]</span></p>
</section>
<section id="modelo-final" class="level2">
<h2 class="anchored" data-anchor-id="modelo-final">Modelo final</h2>
<p>Agora podemos descrever a equação completa (<a href="#eq-regline" class="quarto-xref">Equação&nbsp;3</a>) como:</p>
<p><span id="eq-regfinal"><span class="math display">\[
\hat{y} = 76.10 + 5.86x
\tag{13}\]</span></span></p>
<p>E, graficamente, como na <a href="#fig-dispreg" class="quarto-xref">Figura&nbsp;3</a>, onde observamos o modelo e a equação que descreve a relação entre idade e altura para esses dados simulados. Um outro detalhe importante é que a regressão linear pelo método dos mínimos quadrados obrigatoriamente passará pela média de <span class="math inline">\(x\)</span> e de <span class="math inline">\(y\)</span>, o que também observamos na <a href="#fig-dispreg" class="quarto-xref">Figura&nbsp;3</a> no cruzamento das linhas tracejadas.</p>
<div id="fig-dispreg" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dispreg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="disper_reg.jpeg" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figura&nbsp;3: Modelo de regressão para o problema do exemplo"><img src="disper_reg.jpeg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dispreg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3: Modelo de regressão para o problema do exemplo
</figcaption>
</figure>
</div>
<p>Ainda nos falta calcular se o modelo serve para algo, o <span class="math inline">\(R^2\)</span>, os intervalos de confiança dos coeficientes e a significância dos betas, além de interpretar o modelo.</p>
<div id="wrn-exp" class="callout callout-style-default callout-note callout-titled" title="Pressupostos">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota&nbsp;3: Pressupostos
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A análise de regressão possui pressupostos fortes que não devem ser ignorados. Por uma questão de objetivo, não realizarei a análise dos resíduos ou a verificação dos pressupostos.</p>
</div>
</div>
</div>
</section>
<section id="análise-de-variância-da-regressão" class="level2">
<h2 class="anchored" data-anchor-id="análise-de-variância-da-regressão">Análise de variância da regressão</h2>
<p>Uma forma muito interessante de verificar se o modelo é útil é por meio da análise das variâncias. Interprete “útil” como um modelo que consegue explicar parte da variabilidade dos dados de forma superior a um modelo nulo, que utiliza apenas a média.</p>
<p>Para chegar a isso, podemos descrever a diferença entre os valores observados e a média como: a diferença entre o valor estimado e a média mais a diferença entre o valor observado e o estimado (<a href="#eq-desvios" class="quarto-xref">Equação&nbsp;14</a>).</p>
<p><span id="eq-desvios"><span class="math display">\[
y_i - \bar{y}
=
(\hat{y}_i - \bar{y})
+
(y_i - \hat{y}_i)
\tag{14}\]</span></span></p>
<p>Em outras palavras, o primeiro componente após a igualdade na equação se refere ao modelo e ao quanto suas estimativas estão distantes do valor médio. Já a segunda parte diz respeito ao erro ou resíduo, que é o quanto da explicação não foi capturado pelo modelo (<a href="#fig-errosdomodelo" class="quarto-xref">Figura&nbsp;4</a>).</p>
<div id="fig-errosdomodelo" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-errosdomodelo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="desvios_mod_erro.jpeg" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figura&nbsp;4: "><img src="desvios_mod_erro.jpeg" id="fig-errosdomodelo" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-errosdomodelo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4
</figcaption>
</figure>
</div>
<p>Podemos elevar tudo ao quadrado e somar, obtendo assim a soma de quadrados. Essa também pode ser particionada, conforme a <a href="#eq-sqt" class="quarto-xref">Equação&nbsp;15</a>. Assim teremos a soma de quadrados total <span class="math inline">\((SQT = \sum_{i=1}^{n}(y_i - \bar{y})^2)\)</span>, a soma de quadrados do modelo <span class="math inline">\((SQM =\sum_{i=1}^{n}(\hat{y}_i - \bar{y})^2)\)</span> e a soma de quadrados do erro <span class="math inline">\((SQR= \sum_{i=1}^{n}(y_i - \hat{y})^2)\)</span>.</p>
<p><span id="eq-sqt"><span class="math display">\[
\sum_{i=1}^{n}(y_i - \bar{y})^2=\sum_{i=1}^{n}(\hat{y}_i -
\bar{y})^2+\sum_{i=1}^{n}(y_i - \hat{y})^2
\tag{15}\]</span></span></p>
<section id="coeficiente-de-determinação-r2" class="level3">
<h3 class="anchored" data-anchor-id="coeficiente-de-determinação-r2">Coeficiente de determinação <span class="math inline">\((R^2)\)</span></h3>
<p>Essa métrica é basicamente uma medida do efeito de <span class="math inline">\(x\)</span> em reduzir a variabilidade de <span class="math inline">\(y\)</span>. Pode ser obtida como na <a href="#eq-rdois" class="quarto-xref">Equação&nbsp;16</a>, que é a soma de quadrados do resíduo dividida pela soma de quadrados total.</p>
<p><span id="eq-rdois"><span class="math display">\[
R^2 = 1 - \frac{\sum (y_i - {\color{blue}{\hat{y}_i}})^2}
{\sum (y_i - {\color{red}{\bar{y}}})^2} = 1 - \frac{{\color{blue}{SQR}}}{{\color{red}{SQT}}}
\tag{16}\]</span></span></p>
<p><a href="r2.jpeg" class="lightbox" data-gallery="quarto-lightbox-gallery-5"><img src="r2.jpeg" class="img-fluid"></a></p>
<p>O <span class="math inline">\(R^2\)</span> varia entre <span class="math inline">\(0\)</span> e <span class="math inline">\(1\)</span>. O valor de <span class="math inline">\(0\)</span> é encontrado quando não existe relação linear entre <span class="math inline">\(x\)</span> e <span class="math inline">\(y\)</span>, ou seja, a variável <span class="math inline">\(x\)</span> não explica nada da variação de <span class="math inline">\(y\)</span> e a média de <span class="math inline">\(y\)</span> poderia ser utilizada como estimativa do valor mais provável. Já o valor de <span class="math inline">\(1\)</span> é encontrado quando <span class="math inline">\(x\)</span> explica toda a variação de <span class="math inline">\(y\)</span>. Nesse caso, é possível dizer que mudanças no valor de <span class="math inline">\(x\)</span> também têm efeito no valor de <span class="math inline">\(y\)</span>. Essa “força” pode ser observada na <a href="#fig-rdoisanima" class="quarto-xref">Figura&nbsp;5</a>.</p>
<div id="fig-rdoisanima" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rdoisanima-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="r2_reta_fixa.gif" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figura&nbsp;5: Simulação do coeficiente de determinação"><img src="r2_reta_fixa.gif" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rdoisanima-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5: Simulação do coeficiente de determinação
</figcaption>
</figure>
</div>
</section>
<section id="coeficiente-de-determinação-r2-do-exemplo" class="level3">
<h3 class="anchored" data-anchor-id="coeficiente-de-determinação-r2-do-exemplo">Coeficiente de determinação <span class="math inline">\((R^2)\)</span> do exemplo</h3>
<p>Agora, vou aplicar as equações para determinar o coeficiente de determinação do modelo de regressão entre a idade e a altura.</p>
<p>Primeiro, para calcular o numerador é necessário substituir os valores de <span class="math inline">\(x\)</span> na equação para obter os valores de <span class="math inline">\(\hat{y}\)</span>.</p>
<p><span class="math display">\[
\hat{y}_i= 76.09 + 5.86 * x_i
\]</span></p>
<p><span id="eq-ychapel"><span class="math display">\[
\hat{{y}} =
\begin{bmatrix}
\hat{y}_1 \\
\hat{y}_2 \\
\hat{y}_3 \\
\hat{y}_4 \\
\hat{y}_5 \\
\hat{y}_6
\end{bmatrix}
=
\begin{bmatrix}
105.38 \\
117.10 \\
128.81 \\
140.52 \\
152.24 \\
163.95
\end{bmatrix}
\tag{17}\]</span></span></p>
<p>Agora, podemos fazer o cálculo do denominador, ou seja, a soma de quadrados do erro.</p>
<p><span class="math display">\[
\begin{aligned}
\sum (y_i - \hat{y}_i)^2
= \;&amp; (110-105.38)^2 + (120-117.10)^2 + (120-128.81)^2 \\
&amp; + (135-140.52)^2 + (155-152.24)^2 + (168-163.95)^2
\end{aligned}
\]</span></p>
<p><span class="math display">\[
\sum (y_i - \hat{y}_i)^2= 161.90
\]</span></p>
<p>Já para o numerador é mais simples, uma vez que se utiliza a média.</p>
<p><span class="math display">\[
\begin{aligned}
\sum (y_i - \bar{y})^2
= \;&amp; (110-134.67)^2 + (120-134.67)^2 + (120-134.67)^2 \\
&amp; + (135-134.67)^2 + (155-134.67)^2 + (168-134.67)^2
\end{aligned}
\]</span></p>
<p><span class="math display">\[
\sum(y_i - \bar{y})^2 = 2563.33
\]</span></p>
<p>Por fim, o <span class="math inline">\(R^2\)</span> é encontrado.</p>
<p><span class="math display">\[
R^2= 1 - \frac{161.90}{2563.33} = 0.94
\]</span></p>
</section>
<section id="teste-f" class="level3">
<h3 class="anchored" data-anchor-id="teste-f">Teste <span class="math inline">\(F\)</span></h3>
<p>Outra forma de verificar a variância é por meio do teste F ou análise da variância (ANOVA). A <a href="#tbl-anova" class="quarto-xref">Tabela&nbsp;2</a> apresenta o teste F e o p-valor para o modelo. Aqui não cabem as explicações para os cálculos da ANOVA, embora boa parte seja feita na regressão.</p>
<p>Como resultado principal temos que o p-valor é menor que 0.05, indicando que o modelo é significativo. Portanto, temos evidência de que o modelo é melhor que a média para explicar a variação de <span class="math inline">\(y\)</span>.</p>
<div class="cell">
<div id="tbl-anova" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-anova-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;2: ANOVA para a regressão linear do exemplo
</figcaption>
<div aria-describedby="tbl-anova-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="thxwmqlepo" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#thxwmqlepo table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#thxwmqlepo thead, #thxwmqlepo tbody, #thxwmqlepo tfoot, #thxwmqlepo tr, #thxwmqlepo td, #thxwmqlepo th {
  border-style: none;
}

#thxwmqlepo p {
  margin: 0;
  padding: 0;
}

#thxwmqlepo .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #000000;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#thxwmqlepo .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#thxwmqlepo .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#thxwmqlepo .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#thxwmqlepo .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#thxwmqlepo .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#thxwmqlepo .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#thxwmqlepo .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#thxwmqlepo .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#thxwmqlepo .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#thxwmqlepo .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#thxwmqlepo .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#thxwmqlepo .gt_spanner_row {
  border-bottom-style: hidden;
}

#thxwmqlepo .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#thxwmqlepo .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#thxwmqlepo .gt_from_md > :first-child {
  margin-top: 0;
}

#thxwmqlepo .gt_from_md > :last-child {
  margin-bottom: 0;
}

#thxwmqlepo .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#thxwmqlepo .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#thxwmqlepo .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#thxwmqlepo .gt_row_group_first td {
  border-top-width: 2px;
}

#thxwmqlepo .gt_row_group_first th {
  border-top-width: 2px;
}

#thxwmqlepo .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#thxwmqlepo .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#thxwmqlepo .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#thxwmqlepo .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#thxwmqlepo .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#thxwmqlepo .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#thxwmqlepo .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#thxwmqlepo .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#thxwmqlepo .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#thxwmqlepo .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#thxwmqlepo .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#thxwmqlepo .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#thxwmqlepo .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#thxwmqlepo .gt_left {
  text-align: left;
}

#thxwmqlepo .gt_center {
  text-align: center;
}

#thxwmqlepo .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#thxwmqlepo .gt_font_normal {
  font-weight: normal;
}

#thxwmqlepo .gt_font_bold {
  font-weight: bold;
}

#thxwmqlepo .gt_font_italic {
  font-style: italic;
}

#thxwmqlepo .gt_super {
  font-size: 65%;
}

#thxwmqlepo .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#thxwmqlepo .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#thxwmqlepo .gt_indent_1 {
  text-indent: 5px;
}

#thxwmqlepo .gt_indent_2 {
  text-indent: 10px;
}

#thxwmqlepo .gt_indent_3 {
  text-indent: 15px;
}

#thxwmqlepo .gt_indent_4 {
  text-indent: 20px;
}

#thxwmqlepo .gt_indent_5 {
  text-indent: 25px;
}

#thxwmqlepo .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#thxwmqlepo div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table cell caption-top table table-sm table-striped small" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="gt_heading header">
<td colspan="5" class="gt_heading gt_title gt_font_normal gt_bottom_border">Tabela ANOVA - Teste F</td>
</tr>
<tr class="gt_col_headings even">
<th id="Fonte" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Fonte de variação</th>
<th id="Graus-de-liberdade" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Graus de liberdade<br>
(df)</th>
<th id="Soma-dos-quadrados-(SQ)" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Soma dos quadrados<br>
(SQ)</th>
<th id="Quadrado-médio" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Quadrado médio<br>
QM = SQ/df</th>
<th id="Razão-F" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">valor de F e p-valor</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_center" headers="Fonte">Regressão (x)</td>
<td class="gt_row gt_center" headers="Graus de liberdade">1 (p-1)</td>
<td class="gt_row gt_center" headers="Soma dos quadrados (SQ)">SQT - SQR = 2401.43</td>
<td class="gt_row gt_center" headers="Quadrado médio">2401.43</td>
<td class="gt_row gt_center" headers="Razão F">59.33 (p = 0.00153)</td>
</tr>
<tr class="even">
<td class="gt_row gt_center" headers="Fonte">Resíduo</td>
<td class="gt_row gt_center" headers="Graus de liberdade">4 (n-p)</td>
<td class="gt_row gt_center" headers="Soma dos quadrados (SQ)">161.9</td>
<td class="gt_row gt_center" headers="Quadrado médio">40.48</td>
<td class="gt_row gt_center" headers="Razão F"></td>
</tr>
<tr class="odd">
<td class="gt_row gt_center" headers="Fonte">Total</td>
<td class="gt_row gt_center" headers="Graus de liberdade">5 (n-1)</td>
<td class="gt_row gt_center" headers="Soma dos quadrados (SQ)">2563.33</td>
<td class="gt_row gt_center" headers="Quadrado médio"></td>
<td class="gt_row gt_center" headers="Razão F"></td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</section>
</section>
<section id="significância-dos-betas-do-modelo" class="level2">
<h2 class="anchored" data-anchor-id="significância-dos-betas-do-modelo">Significância dos <span class="math inline">\(\beta\)</span>s do modelo</h2>
<p>Como a variável dependente <span class="math inline">\((y)\)</span> segue uma distribuição normal e as estimativas para <span class="math inline">\(\beta_0\)</span> e <span class="math inline">\(\beta_1\)</span> são obtidas por meio de uma função linear de <span class="math inline">\(y\)</span>, por consequência os coeficientes do modelo também possuem uma distribuição do tipo normal. Isso pode ser observado nas <a href="#eq-distbeta0" class="quarto-xref">Equação&nbsp;18</a> e <a href="#eq-distbeta1" class="quarto-xref">Equação&nbsp;19</a>. Isso significa que, embora tenhamos as estimativas para a melhor reta, poderíamos ter infinitas retas passando entre os dados.</p>
<div class="columns">
<div class="column">
<p><span id="eq-distbeta0"><span class="math display">\[
\beta_0 \sim N(\beta_0, \sigma^2_{\beta_0})
\tag{18}\]</span></span></p>
</div><div class="column">
<p><span id="eq-distbeta1"><span class="math display">\[
\beta_1 \sim N(\beta_1, \sigma^2_{\beta_1})
\tag{19}\]</span></span></p>
</div>
</div>
<p>É possível simular o que seria isso. Partindo dos resultados da <a href="#eq-regfinal" class="quarto-xref">Equação&nbsp;13</a>, utilizo os valores de <span class="math inline">\(\beta\)</span>s para simular 1 mil retas de regressão mudando apenas o erro. Sabemos que em uma regressão linear os erros devem ser normais com média zero e um desvio padrão. Com isso, adiciono erros de forma pseudoaleatória na equação: <span class="math inline">\(y_{i} = 76.09 + 5.86x_{i} + \epsilon_{i}\)</span> e obtenho assim novas estimativas para <span class="math inline">\(y\)</span>. Agora, posso utilizar esse novo <span class="math inline">\(\hat{y}\)</span> e realizar uma regressão com os valores de <span class="math inline">\(x\)</span>, calculando assim novas estimativas de <span class="math inline">\(\beta_{0}\)</span> e <span class="math inline">\(\beta_{1}\)</span>.</p>
<p>As animações abaixo mostram os resultados das simulações. Na imagem superior esquerda temos cada uma das 1000 linhas representando a reta de regressão calculada. Já na direita e na figura inferior da esquerda temos as distribuições de <span class="math inline">\(\beta_0\)</span> e <span class="math inline">\(\beta_1\)</span>, respectivamente. A linha sólida em preto é a distribuição teórica que cada estimador deveria assumir, já as barras representam os valores calculados por meio da simulação. Observamos que, de fato, as distribuições se assemelham a uma curva tipo sino e, portanto, assume-se que são “normais”.</p>
<div class="quarto-layout-panel" data-layout-nrow="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><a href="linhas_regressao.gif" class="lightbox" data-gallery="quarto-lightbox-gallery-7"><img src="linhas_regressao.gif" class="img-fluid"></a></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><a href="beta0.gif" class="lightbox" data-gallery="quarto-lightbox-gallery-8"><img src="beta0.gif" class="img-fluid"></a></p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><a href="beta1.gif" class="lightbox" data-gallery="quarto-lightbox-gallery-9"><img src="beta1.gif" class="img-fluid"></a></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><a href="rss.gif" class="lightbox" data-gallery="quarto-lightbox-gallery-10"><img src="rss.gif" class="img-fluid"></a></p>
</div>
</div>
</div>
<p>Outra importante constatação é que a soma dos resíduos ao quadrado (em inglês RSS: residual sum of squares) dividida pela variância (<span class="math inline">\(\sigma^2\)</span>) dos erros assume uma distribuição do tipo chi-quadrado com graus de liberdade de <span class="math inline">\(n-p\)</span>, onde <span class="math inline">\(n\)</span> é número de amostras e <span class="math inline">\(p\)</span> o número de parâmetros do modelo. Para uma regressão linear simples será sempre <span class="math inline">\(n-2\)</span>, pois sempre há 2 parâmetros (intercepto e coeficiente angular). A distribuição dos resíduos ao quadrado pode ser observada na figura inferior da direita.</p>
<p>A partir do conhecimento de que os estimadores (<span class="math inline">\(\beta\)</span>) possuem distribuição de probabilidade é possível realizar testes de hipóteses sobre suas estimativas. Boa parte do que torna valiosa a regressão é o teste de hipótese dos coeficientes do modelo.</p>
<section id="teste-de-significância-para-beta_0-e-beta_1" class="level3">
<h3 class="anchored" data-anchor-id="teste-de-significância-para-beta_0-e-beta_1">Teste de significância para <span class="math inline">\(\beta_0\)</span> e <span class="math inline">\(\beta_1\)</span></h3>
<p>Talvez o teste de hipótese mais importante de uma regressão seja em relação ao coeficiente angular ou <span class="math inline">\(\beta_1\)</span>, que é o que responde à pergunta sobre se <span class="math inline">\(x\)</span> explica <span class="math inline">\(y\)</span>. Caso <span class="math inline">\(\beta_1\)</span> não seja diferente de <span class="math inline">\(0\)</span>, temos uma linha reta, onde a média de <span class="math inline">\(y\)</span> é suficiente para explicar sua variação e a variável <span class="math inline">\(x\)</span> é inútil.</p>
<p>Essa hipótese pode ser testada considerando:</p>
<p><span class="math inline">\(H_0 : \beta_1 = 0\)</span></p>
<p><span class="math inline">\(H_1 : \beta_1 \ne   0\)</span></p>
<p>A hipótese nula <span class="math inline">\((H_0)\)</span>, ou a suposição inicial, é a de que <span class="math inline">\(\beta_1\)</span> não possui valor diferente de 0; já a alternativa <span class="math inline">\((H_1)\)</span> é a de que o valor de <span class="math inline">\(\beta_1\)</span> é diferente de 0.</p>
<p>Para calcular isso, utiliza-se a estatística <span class="math inline">\(t\)</span> na forma representada pela <a href="#eq-betat" class="quarto-xref">Equação&nbsp;20</a>. Temos a diferença entre o <span class="math inline">\(\beta_1\)</span> estimado e o considerado como verdadeiro, dividida pelo desvio padrão do <span class="math inline">\(\beta_1\)</span>. Assume-se que essa razão possui uma distribuição do tipo <span class="math inline">\(t\)</span> de Student, logo queremos calcular uma estatística <span class="math inline">\(t\)</span>.</p>
<p><span id="eq-betat"><span class="math display">\[
t = \frac{\hat{\beta_1}-\beta_1}{SE(\hat{\beta}_1)} \sim t(N-2)
\tag{20}\]</span></span></p>
<p>Mas utilizar a distribuição <span class="math inline">\(t\)</span>, pelo menos para mim, foi algo que levou tempo até entender. Mas agora sim, na <a href="#fig-tnormchi" class="quarto-xref">Figura&nbsp;6</a> é possível observar o que acontece quando se divide uma distribuição Normal por uma chi-quadrado… Justamente… uma distribuição T. Isso é representado de forma indireta na <a href="#eq-betat" class="quarto-xref">Equação&nbsp;20</a>.</p>
<div id="fig-tnormchi" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tnormchi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="curva_t_da_norm_chi.jpeg" class="lightbox" data-gallery="quarto-lightbox-gallery-11" title="Figura&nbsp;6: Distribuição Normal, Chi-quadrado e T"><img src="curva_t_da_norm_chi.jpeg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tnormchi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6: Distribuição Normal, Chi-quadrado e T
</figcaption>
</figure>
</div>
<p>O <span class="math inline">\(SE(\hat{\beta}_1)\)</span> é o erro padrão do <span class="math inline">\(\beta_1\)</span> e pode ser escrito também como: <span class="math inline">\(SE(\hat{\beta}_1) = \sqrt{\frac{EQM}{\sum(x_1 - \bar{x})^2}}\)</span>, onde <span class="math inline">\(EQM\)</span> é o erro quadrático médio. Esse foi calculado na ANOVA (<a href="#tbl-anova" class="quarto-xref">Tabela&nbsp;2</a>), mas basicamente se obtém como:</p>
<p><span class="math display">\[EQM = \frac{SQR}{(n-p)}\]</span></p>
<p>Já para o <span class="math inline">\(\beta_0\)</span> é um pouco mais complexo e utiliza a equação:</p>
<p><span id="eq-distbeta02"><span class="math display">\[
t = \frac{\hat{\beta_0}-\beta_0}{\sqrt{EQM*(\frac{(\frac{1}{n})+(\bar{x}^2)}{\sum(x_1 - \bar{x})^2})}} \sim t(N-2)
\tag{21}\]</span></span></p>
</section>
<section id="teste-de-significância-para-beta_0-e-beta_1-do-problema" class="level3">
<h3 class="anchored" data-anchor-id="teste-de-significância-para-beta_0-e-beta_1-do-problema">Teste de significância para <span class="math inline">\(\beta_0\)</span> e <span class="math inline">\(\beta_1\)</span> do problema</h3>
<p>Como já descrito acima, o valor encontrado de <span class="math inline">\(\beta_0\)</span> do modelo foi de <span class="math inline">\(76.10\)</span> e <span class="math inline">\(\beta_1\)</span> de <span class="math inline">\(5.86\)</span>.</p>
<p>Primeiro para o <span class="math inline">\(\beta_1\)</span>: se lembrarmos, a expressão <span class="math inline">\(\sum(x_1 - \bar{x})^2\)</span> já foi calculada como denominador para encontrar o <span class="math inline">\(\beta_1\)</span> na <a href="#eq-beta1" class="quarto-xref">Equação&nbsp;7</a>, onde obtivemos o valor de <span class="math inline">\(70\)</span>. Já o <span class="math inline">\(EQM\)</span> é dado por:</p>
<p><span id="eq-eqmbeta1"><span class="math display">\[
EQM = \frac{161.90}{(6-2)}=40.48
\tag{22}\]</span></span></p>
<p>Logo:</p>
<p><span class="math display">\[
SE(\hat{\beta}_1) = \sqrt{\frac{70.48}{70}}  = 0.7604
\]</span></p>
<p>Já para encontrar o valor da estatística <span class="math inline">\(t\)</span> para o <span class="math inline">\(\beta_1\)</span>, calcula-se:</p>
<p><span id="eq-tobs"><span class="math display">\[
t = \frac{5.86-0}{0.7604} = 7.703
\tag{23}\]</span></span></p>
<p>Agora, basta verificar na distribuição <span class="math inline">\(t\)</span> qual a probabilidade de observar um valor de 7.7 ou mais extremo, e se esse valor está dentro da probabilidade de 5%, que é o nível alfa usual.</p>
<p>Na <a href="#fig-disttbeta1" class="quarto-xref">Figura&nbsp;7</a> é plotada a distribuição <span class="math inline">\(t\)</span> com o valor crítico de <span class="math inline">\(t_c\)</span> para um nível de significância de 5% ou 0.05. O <span class="math inline">\(t_c\)</span> diz respeito ao valor na curva <span class="math inline">\(t\)</span> que limita nosso nível de significância, ou seja, para podermos dizer que algo foi significativo a 5% nessa curva, temos que obrigatoriamente observar um valor mais extremo que <span class="math inline">\(\pm 2.78\)</span>.</p>
<p>Como valor de <span class="math inline">\(t\)</span> observado (<span class="math inline">\(t_{obs}\)</span>), temos o valor encontrado na <a href="#eq-tobs" class="quarto-xref">Equação&nbsp;23</a>, que foi de <span class="math inline">\(7.7\)</span>, ou seja, o valor de <span class="math inline">\(t_{obs}\)</span> é maior que o <span class="math inline">\(t_c\)</span>, portanto significativo a 5% de probabilidade de erro.</p>
<p>Também podemos dizer que a probabilidade de encontrar um valor de <span class="math inline">\(t\)</span> igual ao observado é de 0.153% (<span class="math inline">\(p=0.00153\)</span>), ou ainda que, dentro de todos os possíveis valores de <span class="math inline">\(t\)</span> que podemos encontrar, o observado é pouco provável.</p>
<div id="fig-disttbeta1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-disttbeta1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="curva_t_beta.jpeg" class="lightbox" data-gallery="quarto-lightbox-gallery-12" title="Figura&nbsp;7: Distribuição t e verificação de significância estatística do coeficiente angular"><img src="curva_t_beta.jpeg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-disttbeta1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7: Distribuição t e verificação de significância estatística do coeficiente angular
</figcaption>
</figure>
</div>
<p>Para o <span class="math inline">\(\beta_0\)</span>, utiliza-se a <a href="#eq-distbeta02" class="quarto-xref">Equação&nbsp;21</a>, mas primeiro vamos calcular o <span class="math inline">\(SE(\hat{\beta}_0)\)</span>, conforme:</p>
<p><span class="math display">\[
SE(\hat{\beta}_0) = \sqrt{40.48*(\frac{(\frac{1}{6})+(10^2)}{70})} = 8.035
\]</span></p>
<p>Com isso, agora calculamos o <span class="math inline">\(t_{obs}\)</span> para o <span class="math inline">\(\beta_0\)</span>, como:</p>
<p><span class="math display">\[
t = \frac{76.10-0}{8.035} = 9.47
\]</span></p>
<p>E, da mesma forma que para o <span class="math inline">\(\beta_1\)</span>, podemos visualizar a distribuição e a significância estatística (<a href="#fig-disttbeta0" class="quarto-xref">Figura&nbsp;8</a>). Também observamos um valor de <span class="math inline">\(t_{obs}\)</span> mais extremo que o <span class="math inline">\(t_c\)</span> (<span class="math inline">\(9.47&gt;2.776\)</span>), portanto afirmamos que para 5% de probabilidade de erro há diferença significativa.</p>
<div id="fig-disttbeta0" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-disttbeta0-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="curva_t_beta0.jpeg" class="lightbox" data-gallery="quarto-lightbox-gallery-13" title="Figura&nbsp;8: Distribuição t e verificação de significância estatística do intercepto do modelo"><img src="curva_t_beta0.jpeg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-disttbeta0-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;8: Distribuição t e verificação de significância estatística do intercepto do modelo
</figcaption>
</figure>
</div>
</section>
<section id="intervalo-de-confiança-do-beta-e-da-predição-ic" class="level3">
<h3 class="anchored" data-anchor-id="intervalo-de-confiança-do-beta-e-da-predição-ic">Intervalo de confiança do beta e da predição (IC)</h3>
<p>Podemos calcular os limites onde os verdadeiros valores dos <span class="math inline">\(\beta\)</span>s serão encontrados para uma determinada probabilidade: o intervalo de confiança.</p>
<p>O intervalo de confiança pode ser interpretado da seguinte forma: se o experimento fosse repetido indefinidamente, e em cada repetição fosse construído um intervalo de confiança pelo mesmo procedimento, aproximadamente 95% desses intervalos conteriam o verdadeiro valor do parâmetro. Após a coleta dos dados e a construção de um intervalo específico, não é correto afirmar que há 95% de probabilidade de o parâmetro estar dentro desse intervalo.</p>
<p>Para o <span class="math inline">\(\beta_1\)</span> é utilizada a equação:</p>
<p><span class="math display">\[
\hat{\beta}_1
-
t_{\alpha/2,\;n-2}
\,SE\!\left(\hat{\beta}_1\right)
\leq
\beta_1
\leq
\hat{\beta}_1
+
t_{\alpha/2,\;n-2}
\,SE\!\left(\hat{\beta}_1\right)
\]</span></p>
<p>Já para o <span class="math inline">\(\beta_0\)</span> é:</p>
<p><span class="math display">\[
\hat{\beta}_0
-
t_{\alpha/2,\;n-2}
\,SE\!\left(\hat{\beta}_0\right)
\leq
\beta_0
\leq
\hat{\beta}_0
+
t_{\alpha/2,\;n-2}
\,SE\!\left(\hat{\beta}_0\right)
\]</span></p>
<p>Mas, de forma resumida, o IC nada mais é que um parâmetro (nesse caso o valor de <span class="math inline">\(t_c\)</span>) que multiplica uma medida de incerteza (nesse caso o erro padrão, <span class="math inline">\(SE\)</span>). Assim temos que:</p>
<p><span class="math inline">\(CI = t_c* SE(\hat{\beta}_1)\)</span> e <span class="math inline">\(CI = t_c* SE(\hat{\beta}_0)\)</span></p>
<p>E para encontrar essa amplitude de IC, basta somar e subtrair do valor de <span class="math inline">\(\hat{\beta_1}~ou~\hat{\beta_0}\)</span></p>
<p><span class="math inline">\(\beta_1~\pm{CI}\)</span> e <span class="math inline">\(\beta_0~\pm{CI}\)</span></p>
</section>
<section id="intervalo-de-confiança-do-beta-do-modelo" class="level3">
<h3 class="anchored" data-anchor-id="intervalo-de-confiança-do-beta-do-modelo">Intervalo de confiança do beta do modelo</h3>
<p>Para o <span class="math inline">\(\beta_1\)</span> temos:</p>
<p><span class="math inline">\(\hat{\beta_1}= 5.86\)</span></p>
<p><span class="math inline">\(SE(\hat{\beta_1})=0.7604\)</span></p>
<p><span class="math inline">\(t_c = 7.703\)</span></p>
<p>E o IC vai ser:</p>
<p><span class="math display">\[
5.86 - (2.776 * 0.7604) \leq \beta_1 \leq 5.86 + (2.776 * 0.7604)
\]</span></p>
<p><span class="math display">\[
3.74913 \leq \beta_1 \leq 7.97087
\]</span></p>
<p>Ou,</p>
<p><span class="math display">\[
\beta_1 = 5.86 \pm{2.11087}
\]</span></p>
<p>Para o <span class="math inline">\(\beta_0\)</span> será a mesma coisa:</p>
<p><span class="math inline">\(\hat{\beta_0}= 76.1\)</span></p>
<p><span class="math inline">\(SE(\hat{\beta_0})=8.035\)</span></p>
<p><span class="math inline">\(t_c = 9.47\)</span></p>
<p>E o IC vai ser:</p>
<p><span class="math display">\[
76.1- (2.776 * 8.035) \leq \beta_0 \leq 76.1 + (2.776 * 8.035)
\]</span></p>
<p><span class="math display">\[
53.79484\leq \beta_0 \leq 98.40516
\]</span></p>
<p>Ou,</p>
<p><span class="math display">\[
\beta_0 = 76.1 \pm{22.30516}
\]</span></p>
</section>
<section id="intervalo-de-confiança-para-resposta-média" class="level3">
<h3 class="anchored" data-anchor-id="intervalo-de-confiança-para-resposta-média">Intervalo de confiança para resposta média</h3>
<p>Podemos também calcular “bandas” de confiança para a reta de regressão e os valores médios por todo o domínio de <span class="math inline">\(x\)</span>.</p>
<p>Para isso vamos usar a <a href="#eq-icmedia" class="quarto-xref">Equação&nbsp;24</a> e o melhor… quase tudo já foi calculado. A única “entrada” agora será com valores de <span class="math inline">\(x\)</span> que podem ser novos e é dado por <span class="math inline">\(x_0\)</span>, mas uso os mesmos.</p>
<p><span id="eq-icmedia"><span class="math display">\[
\hat{y}(x_0)
\pm
t_{\alpha/2,\;n-2}
\sqrt{
EQM
\left(
\frac{1}{n}
+
\frac{(x_0-\bar{x})^2}
{\sum_{i=1}^{n}(x_i-\bar{x})^2}
\right)
}
\tag{24}\]</span></span></p>
</section>
<section id="intervalo-de-confiança-para-resposta-média-do-modelo" class="level3">
<h3 class="anchored" data-anchor-id="intervalo-de-confiança-para-resposta-média-do-modelo">Intervalo de confiança para resposta média do modelo</h3>
<p>Como vou utilizar os mesmos valores de <span class="math inline">\(x\)</span>, os valores de <span class="math inline">\(\hat{y}\)</span> já foram calculados em <a href="#eq-ychapel" class="quarto-xref">Equação&nbsp;17</a>. Também temos os desvios de <span class="math inline">\(x\)</span> em <a href="#eq-somadesviox" class="quarto-xref">Equação&nbsp;12</a>, bem como o somatório, o <span class="math inline">\(t\)</span> crítico em <a href="#fig-disttbeta1" class="quarto-xref">Figura&nbsp;7</a> e o <span class="math inline">\(EQM\)</span> em <a href="#eq-eqmbeta1" class="quarto-xref">Equação&nbsp;22</a>. Os valores que vão mudar serão o <span class="math inline">\(\hat{y}\)</span> e o desvio de <span class="math inline">\(x\)</span> (<a href="#eq-yychap" class="quarto-xref">Equação&nbsp;25</a> e <a href="#eq-desvioxx" class="quarto-xref">Equação&nbsp;26</a>); isso é denotado na equação geral do IC com o índice <span class="math inline">\(i\)</span>.</p>
<p><span id="eq-yychap"><span class="math display">\[\hat{y}(x_0)_i = \begin{bmatrix}
105.38\\
117.10\\
128.81\\
140.52\\
152.24\\
163.95
\end{bmatrix}
\tag{25}\]</span></span></p>
<p><span id="eq-desvioxx"><span class="math display">\[
(x_0-\bar{x})^2_i= \begin{bmatrix}
25\\
9\\
1\\
1\\
9\\
25
\end{bmatrix}
\tag{26}\]</span></span></p>
<p><span class="math display">\[
\begin{aligned}
IC_{inf}=
\hat{y}(x_0)_i
-
(2.776*
\sqrt{
40.48
\left(
\frac{1}{6}
+
\frac{
(x_0-\bar{x})^2_i
}{70}
\right))
}
&amp;=
\begin{bmatrix}
92.599\\
107.499\\
121.297\\
133.011\\
142.642\\
151.170
\end{bmatrix}
\end{aligned}
\]</span></p>
<p>e</p>
<p><span class="math display">\[
\begin{aligned}
IC_{sup}=
\hat{y}(x_0)_i
+
(2.776*
\sqrt{
40.48
\left(
\frac{1}{6}
+
\frac{
(x_0-\bar{x})^2_i
}{70}
\right))
}
&amp;=
\begin{bmatrix}
118.163\\
126.692\\
136.322\\
148.037\\
161.834\\
176.735
\end{bmatrix}
\end{aligned}
\]</span></p>
<p>Por fim, podemos plotar esses pontos e gerar as “bandas” ou a região de confiança (<a href="#fig-bandaconfi" class="quarto-xref">Figura&nbsp;9</a>).</p>
<div id="fig-bandaconfi" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bandaconfi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="final.jpeg" class="lightbox" data-gallery="quarto-lightbox-gallery-14" title="Figura&nbsp;9: Intervalo de confiança para a linha média do modelo"><img src="final.jpeg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bandaconfi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;9: Intervalo de confiança para a linha média do modelo
</figcaption>
</figure>
</div>
</section>
</section>
<section id="resultado-final-da-análise" class="level2">
<h2 class="anchored" data-anchor-id="resultado-final-da-análise">Resultado final da análise</h2>
<p>Agora, podemos descrever o resultado da análise em forma de texto, o que pode ser usado para descrever qualquer regressão.</p>
<p>Exemplo de descrição de resultado:</p>
<p>Para verificar o efeito da idade (variável independente) sobre a altura (variável dependente) foi realizada uma análise de regressão linear simples. O modelo teórico é dado por: <span class="math inline">\(Altura = \beta_{0} + \beta_{1} Idade + \epsilon\)</span>.</p>
<p>O modelo é estatisticamente significativo e explica uma parte substancial da variância (<span class="math inline">\(R^2=0.94,~F(1,4) = 59.33,~p = 0.0015\)</span>). O efeito da idade foi significativo e positivo: a cada aumento de uma unidade na idade, a altura aumenta, em média, 5.86 cm (<span class="math inline">\(CI [3.75,7.97],~t(4) = 7.70,~p = 0.0015\)</span>).</p>
<p>Sobre o intercepto, temos que ter cuidado. Nosso modelo diz que, para uma pessoa com idade igual a zero, a sua altura é de 76.1 cm (<span class="math inline">\(CI[53.79,98.41],~t(4)=9.47,~p=0.0007\)</span>). A interpretação, nesse caso, deve ser baseada na área de conhecimento; neste exemplo, a menos que tenhamos um gigante, essa interpretação não faz sentido, já que, biologicamente, até onde sei, ao nascer (idade zero) as pessoas têm comprimento abaixo desse valor.</p>
<p>E isso tudo é resumido na <a href="#fig-finalpronto" class="quarto-xref">Figura&nbsp;10</a>.</p>
<div id="fig-finalpronto" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-finalpronto-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="disper_reg_smot.jpeg" class="lightbox" data-gallery="quarto-lightbox-gallery-15" title="Figura&nbsp;10: Modelo final"><img src="disper_reg_smot.jpeg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-finalpronto-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;10: Modelo final
</figcaption>
</figure>
</div>
<p>Então quer dizer que a idade ocasiona o aumento da altura? Ou seja, ficar velho te deixa alto?</p>
</section>
</section>
<section id="regressão-linear-simples-define-causa-bônus" class="level1">
<h1>Regressão linear simples define causa? (bônus)</h1>
<p>Bem, a resposta para a pergunta sobre causa é complicada. Por definição, a regressão linear <strong>não</strong> expressa causa. Em um modelo de regressão significativo, o que temos é que a variável <span class="math inline">\(y\)</span> possui associação com a variável <span class="math inline">\(x\)</span>, mas não que <span class="math inline">\(x\)</span> é o responsável por causar <span class="math inline">\(y\)</span>. Parece confuso, mas faz todo sentido. Isso acontece porque não temos acesso a todas as variáveis que podem estar interferindo no fenômeno e, portanto, nas observações. Dentre muitas formas de definir causa, podemos dizer que a causa possui 3 componentes: 1) direcionalidade, 2) temporalidade e 3) reprodutibilidade. Esses componentes são fundamentais para estabelecer uma relação causal, algo que a regressão linear simples não pode garantir, por si só.</p>
<p>Isso não significa que a regressão não é importante, apenas que devemos ter cuidado ao dizer que as mudanças observadas na variável dependente são <strong>causadas</strong> pela variável independente.</p>
<p>Na <a href="#fig-dag" class="quarto-xref">Figura&nbsp;11</a> há exemplos de algumas relações que podem ser encontradas. Como podemos observar, a regressão linear corresponde ao subgráfico com a relação direta. Porém, não há como saber se as demais relações estão ocorrendo. Por exemplo, poderíamos ter em nossa relação direta um confundidor, que é uma variável com efeito tanto em <span class="math inline">\(x\)</span> quanto em <span class="math inline">\(y\)</span> e que, portanto, leva à observação da relação entre <span class="math inline">\(x\)</span> e <span class="math inline">\(y\)</span> pelo modelo. Essa pode ser uma das explicações para as correlações espúrias. Também podemos ter uma variável mediadora, ou seja, responsável por mediar uma parte da variação entre <span class="math inline">\(x\)</span> e <span class="math inline">\(y\)</span>, além da variação direta. E, por fim, temos a moderação, em que outra variável pode estar moderando a relação entre <span class="math inline">\(x\)</span> e <span class="math inline">\(y\)</span>. Em todos os casos, se estamos usando apenas uma regressão linear simples, podemos estar suscetíveis a não observar essa variável oculta. Por isso: regressão não implica causa.</p>
<div id="fig-dag" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dag-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="plot_causa.jpeg" class="lightbox" data-gallery="quarto-lightbox-gallery-16" title="Figura&nbsp;11: Possíveis relações entre variáveis"><img src="plot_causa.jpeg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dag-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11: Possíveis relações entre variáveis
</figcaption>
</figure>
</div>
<p>Ainda assim, com os avanços dos estudos, essas variáveis ocultas podem ir sendo descobertas e aprimorando a nossa teoria… Incrível!</p>
<div class="callout callout-style-default callout-important callout-titled" title="Ajuda estatística">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Ajuda estatística
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Boa parte dos cálculos e das dúvidas foi resolvida graças à ajuda de Diogo Bolzan (um quase estatístico da UFRGS).</p>
</div>
</div>
</div>



</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> De volta ao topo</a><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">Referências</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-altay" class="csl-entry" role="listitem">
Altay L. Souza. 2025. <em>Regressão Linear III - Descrever, Explicar e Predizer na RLinear</em>. <a href="https://www.youtube.com/watch?v=mQpnsYh4JQA" class="uri">Https://www.youtube.com/watch?v=mQpnsYh4JQA</a>.
</div>
<div id="ref-b053c0e7-e2d5-3dd5-93ba-a1adab8d3d90" class="csl-entry" role="listitem">
Box, Joan Fisher. 1981. <span>«Gosset, Fisher, and the t Distribution»</span>. <em>The American Statistician</em> 35 (2): 61–66. <a href="http://www.jstor.org/stable/2683142">http://www.jstor.org/stable/2683142</a>.
</div>
<div id="ref-alma991020382257805181" class="csl-entry" role="listitem">
Douglas C. Montgomery, G. Geoffrey Vining, Elizabeth A. Peck. 2021. <em>Introduction to Linear Regression Analysis</em>. Wiley. <a href="https://www.perlego.com/book/2237423/introduction-to-linear-regression-analysis-pdf">https://www.perlego.com/book/2237423/introduction-to-linear-regression-analysis-pdf</a>.
</div>
<div id="ref-guimaraes2022regression" class="csl-entry" role="listitem">
Guimarães, Alysson. 2022. <span>«Princípios da Regressão Linear»</span>. Em <em>https://k3ybladewielder.medium.com</em>. <a href="https://k3ybladewielder.medium.com/p-3ab26a7b4340">https://k3ybladewielder.medium.com/p-3ab26a7b4340</a>.
</div>
<div id="ref-kasza" class="csl-entry" role="listitem">
Kasza, Jessica, e Rory Wolfe. 2014. <span>«Interpretation of commonly used statistical regression models»</span>. <em>Respirology</em> 19 (1): 14–21. https://doi.org/<a href="https://doi.org/10.1111/resp.12221">https://doi.org/10.1111/resp.12221</a>.
</div>
<div id="ref-setosa_linear_regression" class="csl-entry" role="listitem">
Setosa. 2018. <em>Linear Regression</em>. <a href="https://setosa.io/ev/linear-regression/" class="uri">Https://setosa.io/ev/linear-regression/</a>.
</div>
<div id="ref-shmueli" class="csl-entry" role="listitem">
Shmueli, Galit. 2010. <span>«<span>To Explain or to Predict?</span>»</span> <em>Statistical Science</em> 25 (3): 289–310. <a href="https://doi.org/10.1214/10-STS330">https://doi.org/10.1214/10-STS330</a>.
</div>
<div id="ref-joram_soch_2025_18096132" class="csl-entry" role="listitem">
<span class="nocase">Soch, Joram, The Book of Statistical Proofs, Karahan Sarıtaş, et al.</span> 2025. <em>StatProofBook/StatProofBook.github.io: StatProofBook 2025</em>. Versão 2025. Zenodo, released dezembro. <a href="https://doi.org/10.5281/zenodo.18096132">https://doi.org/10.5281/zenodo.18096132</a>.
</div>
<div id="ref-wilber2022linear" class="csl-entry" role="listitem">
Wilber, Jared. 2022. <em>Linear Regression: A Visual Introduction to (Almost) Everything You Should Know</em>. <a href="https://mlu-explain.github.io/linear-regression/" class="uri">Https://mlu-explain.github.io/linear-regression/</a>.
</div>
</div></section><section class="quarto-appendix-contents" id="quarto-citation"><h2 class="anchored quarto-appendix-heading">Citação</h2><div><div class="quarto-appendix-secondary-label">BibTeX</div><pre class="sourceCode code-with-copy quarto-appendix-bibtex"><code class="sourceCode bibtex">@online{frosi2026,
  author = {Frosi, Gustavo},
  title = {Do ponto à linha: criando uma regressão para além de clicar
    em botão},
  date = {2026-07-06},
  url = {https://gustavofrosi.com.br/recap/2026-07-06-reg-line-conta/},
  doi = {10.59350/xp1jx-gs759},
  langid = {pt}
}
</code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre><div class="quarto-appendix-secondary-label">Por favor, cite este trabalho como:</div><div id="ref-frosi2026" class="csl-entry quarto-appendix-citeas" role="listitem">
Frosi, Gustavo. 2026. <span>“Do ponto à linha: criando uma regressão
para além de clicar em botão.”</span> July 6. <a href="https://doi.org/10.59350/xp1jx-gs759">https://doi.org/10.59350/xp1jx-gs759</a>.
</div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/gustavofrosi\.com\.br");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Website made with quarto © 2026 by Gustavo Frosi is licensed under CC BY-SA 4.0.</p>
</div>   
    <div class="nav-footer-center">
<p><img src="ima/FS.png" width="25" height="25"></p>
</div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/FGu5tav0">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="mailto:gustavofrosi@hotmail.com">
      <i class="bi bi-envelope" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>